### ISSUE TITLE
assertion fired

### ISSUE THREAD

**Issue by ethem-kinginthenorth** [NVIDIA/PyProf#36]
I am getting the below assertion. So for any not supported operation, is there an assertion?

Traceback (most recent call last):
  File "prof.py", line 277, in <module>
    main()
  File "prof.py", line 242, in main
    xx = foo(mod, op, d)
  File "prof.py", line 148, in foo
    xx = LogSoftmax(d)
  File "/workspace/pyprof/PyProf-master/pyprof/prof/softmax.py", line 89, in __init__
    assert (mod == "torch.nn.functional")
AssertionError

**Comment by adityaiitb** [comment]
No, for unsupported operations (and there are a few), the code is pass through. No assertions will fire. You will see `na` (not available) in the output.

For the current assertion, if its ok can you share the `net.dict` file?

**Comment by ethem-kinginthenorth** [comment]
the file is around 300mb, I am not sure if I can upload it here.

**Comment by ethem-kinginthenorth** [comment]
I found a 50mb version with the same error. I will be uploading here.

**Comment by ethem-kinginthenorth** [comment]
[out_o0.zip](https://github.com/NVIDIA/PyProf/files/4833813/out_o0.zip)
Seems like zip is making the file much smaller.

**Comment by adityaiitb** [comment]
@ethem-kinginthenorth 

Thanks a lot for using the tool and reporting the bug. I was able to reproduce the error. I found two issues.
- The first is related to `torch.log_softmax`. Its a valid function but is actually undocumented. Its being fixed in this PR https://github.com/NVIDIA/PyProf/pull/38
- The other is related to `torch.any`. I am looking into it.

**Comment by debermudez** [comment]
All fixes for this issue are in the codebase now. Closing

**Comment by smartcat2010** [comment]
> All fixes for this issue are in the codebase now. Closing

I still have the assertion error of "any":
`
"649","fprop","0","torch.nn.functional","relu","modern::vectorized_elementwise_kernel","T=(32,2048,7,7),fp16,","24032"
"650","fprop","0","torch.nn.functional","adaptive_avg_pool2d","reduce_kernel","T=[(32,2048,7,7)],['float16']","40416"
"651","fprop","0","torch.nn.functional","bias","modern::unrolled_elementwise_kernel","M=1000,N=32,fp16,","5920"
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/pyprof/prof/__main__.py", line 21, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/pyprof/prof/prof.py", line 242, in main
    xx = foo(mod, op, d)
  File "/opt/conda/lib/python3.6/site-packages/pyprof/prof/prof.py", line 74, in foo
    xx = Linear(d)
  File "/opt/conda/lib/python3.6/site-packages/pyprof/prof/linear.py", line 110, in __init__
    assert any(x in d.name for x in Linear.biasKernels)
AssertionError`

Enviroment: 
NVIDIA V100 GPU Card;
Utuntu 18.04
Docker:   docker pull nvcr.io/nvidia/pytorch:20.06-py3
When running in the docker, I "git clone" pyprof and "python setup.py install"
Then I profile "PyProf/pyprof/examples/imagenet/imagenet.py", in the step "python -m pyprof.prof --csv net.dict" the above error shows.

**Comment by adityaiitb** [comment]
If you don't mind, can you share the `net.dict` file. The issue is probably not related to `torch.any`, but seems to be related to a new bias kernel.

**Comment by adityaiitb** [comment]
@smartcat2010 

The bug is not related to `torch.any`, Linear or Bias. Its related to PyTorch sequence id during backward propagation. I have created a new bug. Its being tracked here. https://github.com/NVIDIA/PyProf/issues/46
