### ISSUE TITLE
Backward sequence id (softmax incorrectly inferred as linear)

### ISSUE THREAD

**Issue by adityaiitb** [NVIDIA/PyProf#46]
`
"649","fprop","0","torch.nn.functional","relu","modern::vectorized_elementwise_kernel","T=(32,2048,7,7),fp16,","24032"
"650","fprop","0","torch.nn.functional","adaptive_avg_pool2d","reduce_kernel","T=[(32,2048,7,7)],['float16']","40416"
"651","fprop","0","torch.nn.functional","bias","modern::unrolled_elementwise_kernel","M=1000,N=32,fp16,","5920"
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/pyprof/prof/__main__.py", line 21, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/pyprof/prof/prof.py", line 242, in main
    xx = foo(mod, op, d)
  File "/opt/conda/lib/python3.6/site-packages/pyprof/prof/prof.py", line 74, in foo
    xx = Linear(d)
  File "/opt/conda/lib/python3.6/site-packages/pyprof/prof/linear.py", line 110, in __init__
    assert any(x in d.name for x in Linear.biasKernels)
AssertionError`

Enviroment: 
NVIDIA V100 GPU Card;
Utuntu 18.04
Docker:   docker pull nvcr.io/nvidia/pytorch:20.06-py3
When running in the docker, I "git clone" pyprof and "python setup.py install"
Then I profile "PyProf/pyprof/examples/imagenet/imagenet.py", in the step "python -m pyprof.prof --csv net.dict" the above error shows.

_Originally posted by @smartcat2010 in https://github.com/NVIDIA/PyProf/issues/36#issuecomment-653349012_

**Comment by adityaiitb** [comment]
@smartcat2010
Are you using PyTorch version 1.6 (or the latest Nvidia docker 20.06)?  It appears there were changes to the PyTorch internal `sequence id` which is breaking the correlation from back propagation to forward propagation in PyProf.

Temporarily can you use PyTorch 1.5 or the Nvidia 20.03 docker.

**Comment by aman26kbm** [comment]
Aditya, I'm seeing this issue in other networks as well, with 20.06 version of the container. I saw this in Resnet and NCF. It'll be great if you can fix this soon :)

**Comment by adityaiitb** [comment]
We are trying to understand the changes in PyTorch. AFAI can tell, this might take a while to get resolved. If its not too big an issue I would suggest using PyTorch 1.5 / Nvidia docker 20.03.

**Comment by aman26kbm** [comment]
Aditya, is the fix supposed to be in PyTorch or is it possible to handle this at the PyProf level? As in, do we need PyTorch code to be updated for us to proceed or can PyProf be modified so it works with updated PyTorch?

**Comment by aman26kbm** [comment]
Just trying to understand the nature of the fix.

**Comment by adityaiitb** [comment]
We don't know the answer to that question i.e. which component needs to be fixed/rolled back. I have sent a repro code to the PyTorch team.

**Comment by shangw-nvidia** [comment]
Hi @adityaiitb , we've been seen another problem on the 20.06 docker image for Ampere where the conv backward pass was incorrectly labeled as "batch_norm" (this is on a resnet-based model):

The .dict file contains:
```
{'kShortName': 'cudnn::cnn::wgrad_alg1_engine', 'kDuration': 488158, 'layer': [], 'trace': [], 'reprMarkers': [], 'marker': [], 'seqMarker': ['cudnn_convolution_backward, seq = 0', 'CudnnConvolutionBackward, seq = 48098'], 'callid': ['na'], 'input_callids': ['na', 'na'], 'seqId': [48098], 'subSeqId': 2, 'altSeqId': [], 'dir': 'bprop', 'mod': ['na', 'na'], 'op': ['cudnn_convolution', 'CudnnConvolution'], 'tid': 2148787968, 'device': 0, 'stream': 7, 'grid': (2, 3, 13), 'block': (8, 8, 1), 'kLongName': 'void cudnn::cnn::wgrad_alg1_engine<float, 128, 5, 5, 3, 3, 3, false, true>(int, int, int, float const*, int, float*, float const*, kernel_grad_params, unsigned long long, int, float, float, int, int, int*, int*, int, int)'}
```
Whereas the .csv file contains:
```
512	bprop	2	torch.nn.functional	batch_norm	cudnn::cnn::wgrad_alg1_engine	T=(32,72,29,53),fp32,	488158	62779	dram	[484586]	['484583:0']
```

Would you be able to provide an timeline on when we could expect pyprof to be able to work with 20.06? This has pretty high priority since Ampere only works with 20.06 or higher.

**Comment by adityaiitb** [comment]
hi Shawn,

We understand. Thanks to @ilia-cher and @ngimel at PyTorch for fixing the issue promptly. ([Pull request](https://github.com/pytorch/pytorch/pull/42565), [Commit](https://github.com/pytorch/pytorch/commit/f9a6c14364956bc72ecaea7441867e9cc07805f2)).

AFAIU, the fix is available in a nightly build but not yet in a formal dot release / Nvidia docker. Therefore, one way would be to build PyTorch from source with the latest CUDA / cuBLAS / cuDNN etc. On our end, we are doing some testing and thinking how to make the solution more seamless for end users.

@dzier @mcarilli might know more.

**Comment by adityaiitb** [comment]
Fixed in PyTorch > 1.6.

**Comment by karthi0804** [comment]
Hi, 
I am still getting error in Pytorch 1.8. I am profling GNN model using torch-geometric. someone pls help me.

`6200 bprop vectorized_elementwise_kernel T=(10378,64),D=-2,I=461128,fp32, 0
6201 bprop indexAddLargeIndex T=(10378,64),D=-2,I=461128,fp32, 0
6202 fprop unrolled_elementwise_kernel na=na, 0
6203 bprop vectorized_elementwise_kernel [10378,64]fp32 664192
6204 bprop sgemm_32x32x32_NN_vec M=8,N=10378,K=64,fp32, 10627072
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/pyprof/prof/__main__.py", line 21, in <module>
    main()
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/pyprof/prof/prof.py", line 253, in main
    xx = foo(mod, op, d)
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/pyprof/prof/prof.py", line 75, in foo
    xx = Linear(d)
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/pyprof/prof/linear.py", line 115, in __init__
    assert any(x in d.name for x in Linear.biasKernels), f"Kernel name: {d.name}"
AssertionError: Kernel name: scal_kernel
`

**Comment by adityaiitb** [comment]
hi,

Thanks for reporting. Can you share the `net.dict` file? I can take a look.

**Comment by karthi0804** [comment]
> hi,
> 
> Thanks for reporting. Can you share the `net.dict` file? I can take a look.

sure. [pls find here](https://gist.github.com/karthi0804/f9beb2bc05929729012e6616fee65b2b)

**Comment by adityaiitb** [comment]
hi Karthikeyan,

A few observations and remarks.

a) Are you using the branch `main`? That is the default branch. Can you switch to that branch and reinstall.
b) In your earlier message the error occurred after around 6200 kernels. However, the `net.dict` file you shared has only 73 kernels.
c) I ran the `net.dict` and ran into a different error. The error happens on line 48 due to `torch.zeros_like` which is confusing. According to the [docs](https://pytorch.org/docs/stable/generated/torch.zeros_like.html), the first input to `torch.zeros_like` should be a tensor. However, the first argument appears to be an int with value 0.

Can you please double check.

**Comment by karthi0804** [comment]
> hi Karthikeyan,
> 
> A few observations and remarks.
> 
> a) Are you using the branch `main`? That is the default branch. Can you switch to that branch and reinstall.
> b) In your earlier message the error occurred after around 6200 kernels. However, the `net.dict` file you shared has only 73 kernels.
> c) I ran the `net.dict` and ran into a different error. The error happens on line 48 due to `torch.zeros_like` which is confusing. According to the [docs](https://pytorch.org/docs/stable/generated/torch.zeros_like.html), the first input to `torch.zeros_like` should be a tensor. However, the first argument appears to be an int with value 0.
> 
> Can you please double check @karthi0804

1.  I am using the main branch.
2. Sorry my mistake. I didn't copy the dict file fully into gist. Please have a look at the [new file](https://drive.google.com/file/d/1oqRDHekVwol3n7PHdEjvDHOCmQE-CJ2y/view?usp=sharing) now.

**Comment by adityaiitb** [comment]
Created a new issue #162, since this is not related to bprop sequence ids.
